@getUrl=https://example.com/api/
@version=1.1
&ExampleGet
GET {{getUrl}} {{version}}
Accept: application/json

@postUrl=https://example.com/api/create/
&ExamplePost
POST {{postUrl}} {{version}}
Content-Type: application/json
Accept: application/json

{
    "name": "Some One",
    "email": "someone@example.com"
}
