@url=https://google.com
@version=1.1
&Google
GET {{url}} {{version}}
Accept: application/json
Content-Type: application/json

GET {{url}} 1.0

POST {{url}} 1.1
Content-Type: application/json
Accept: application/json

{
    "id": 0,
    "name": "Example",
    "email": "someone@gmail.com"
}

PATCH {{url}} 1.1
Content-Language: en
Content-Type: application/json
Accept: application/json
Accept-Language: en
Accept-Patch: application/merge-patch+json

{
    "id": 0,
    "email": "some.one@gmail.com"
}
